version: '3.8'

services:
  relayer-db:
    container_name: relayer-db
    hostname: relayer-db
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-relayer}
    volumes:
      - relayer-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  relayer-db:
